from fpdf import FPDF
import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 20)
        self.cell(0, 10, 'Smart-Spider | SEO Audit Report', 0, 1, 'C')
        self.ln(5)
        
        # Line break
        self.set_draw_color(59, 130, 246) # Blue color
        self.set_line_width(1)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Smart-Spider AI', 0, 0, 'C')

def create_pdf(url, data, score):
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. Audit Summary
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"Target: {url}", 0, 1)
    
    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(100)
    pdf.cell(0, 10, f"Scan Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.ln(5)

    # 2. Score Badge
    pdf.set_font("Arial", "B", 50)
    if score > 80:
        pdf.set_text_color(16, 185, 129) # Green
    elif score > 50:
        pdf.set_text_color(245, 158, 11) # Orange
    else:
        pdf.set_text_color(239, 68, 68) # Red
        
    pdf.cell(0, 20, f"{score}/100", 0, 1, 'C')
    
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(0)
    pdf.cell(0, 10, "OVERALL HEALTH SCORE", 0, 1, 'C')
    pdf.ln(10)

    # 3. Technical Metrics Table
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Technical Diagnostics", 0, 1)
    
    # Table Header
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(95, 10, "Metric", 1, 0, 'C', 1)
    pdf.cell(95, 10, "Status", 1, 1, 'C', 1)
    
    # Table Rows
    metrics = [
        ("Server Response Code", str(data['status_code'])),
        ("Load Speed", f"{data['load_time']} seconds"),
        ("Total Images", str(len(data['images']))),
        ("Internal Links", str(data['internal_links_count'])),
        ("Title Tag", "Present" if data['title'] != "Missing" else "MISSING"),
        ("Meta Description", "Present" if data['meta_desc'] != "Missing" else "MISSING"),
    ]
    
    pdf.set_font("Arial", "", 10)
    for metric, value in metrics:
        pdf.cell(95, 10, metric, 1)
        pdf.cell(95, 10, value, 1, 1)
        
    pdf.ln(10)
    
    # 4. AI Vision Insights (New Feature)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "AI Vision Analysis", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    missing_alt = len([img for img in data['images'] if not img['alt']])
    pdf.multi_cell(0, 8, f"The Smart-Spider Vision system analyzed {len(data['images'])} visual assets. We detected {missing_alt} images missing 'alt-text' tags, which impacts accessibility and SEO rankings.")
    
    pdf.ln(5)
    pdf.set_text_color(100)
    pdf.cell(0, 10, "*** End of Official Audit Report ***", 0, 1, 'C')

    return pdf.output(dest='S').encode('latin-1')