from fpdf import FPDF
import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 20)
        self.cell(0, 10, 'Smart-Spider | SEO Audit Report', 0, 1, 'C')
        self.ln(5)
        
        # Line break
        self.set_draw_color(59, 130, 246) # Blue color
        self.set_line_width(1)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Smart-Spider AI', 0, 0, 'C')

# ---> THE FIX IS HERE: Added action_plan=None to the arguments <---
def create_pdf(url, data, score, action_plan=None):
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. Audit Summary
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"Target: {url}", 0, 1)
    
    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(100)
    pdf.cell(0, 10, f"Scan Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.ln(5)

    # 2. Score Badge
    pdf.set_font("Arial", "B", 50)
    if score > 80:
        pdf.set_text_color(16, 185, 129) # Green
    elif score > 50:
        pdf.set_text_color(245, 158, 11) # Orange
    else:
        pdf.set_text_color(239, 68, 68) # Red
        
    pdf.cell(0, 20, f"{score}/100", 0, 1, 'C')
    
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(0)
    pdf.cell(0, 10, "OVERALL HEALTH SCORE", 0, 1, 'C')
    pdf.ln(10)

    # 3. Technical Metrics Table
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Technical Diagnostics", 0, 1)
    
    # Table Header
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(95, 10, "Metric", 1, 0, 'C', 1)
    pdf.cell(95, 10, "Status", 1, 1, 'C', 1)
    
    # Table Rows
    metrics = [
        ("Server Response Code", str(data['status_code'])),
        ("Load Speed", f"{data['load_time']} seconds"),
        ("Total Images", str(len(data['images']))),
        ("Internal Links", str(data['internal_links_count'])),
        ("Title Tag", "Present" if data['title'] != "Missing" else "MISSING"),
        ("Meta Description", "Present" if data['meta_desc'] != "Missing" else "MISSING"),
    ]
    
    pdf.set_font("Arial", "", 10)
    for metric, value in metrics:
        pdf.cell(95, 10, metric, 1)
        pdf.cell(95, 10, value, 1, 1)
        
    pdf.ln(10)
    
    # 3.5 Security Posture Table
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Trust & Security Posture (DevSecOps)", 0, 1)
    
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(95, 10, "Security Header", 1, 0, 'C', 1)
    pdf.cell(95, 10, "Status", 1, 1, 'C', 1)
    
    sec = data.get('security_headers', {})
    sec_metrics = [
        ("Strict-Transport-Security (HSTS)", "ACTIVE" if sec.get('hsts') else "MISSING"),
        ("X-Frame-Options", "ACTIVE" if sec.get('x_frame') else "MISSING"),
        ("X-Content-Type-Options", "ACTIVE" if sec.get('x_content_type') else "MISSING"),
        ("Content-Security-Policy (CSP)", "ACTIVE" if sec.get('csp') else "MISSING"),
    ]
    
    for metric, status in sec_metrics:
        pdf.set_font("Arial", "", 10)
        pdf.cell(95, 10, metric, 1)
        
        # Color code the status text
        if status == "ACTIVE":
            pdf.set_text_color(16, 185, 129) # Green
            pdf.set_font("Arial", "B", 10)
        else:
            pdf.set_text_color(239, 68, 68) # Red
            pdf.set_font("Arial", "B", 10)
            
        pdf.cell(95, 10, status, 1, 1, 'C')
        pdf.set_text_color(0) # Reset to black
        
    pdf.ln(10)
    
    # 4. AI Vision Insights 
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "AI Vision Analysis", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    missing_alt = len([img for img in data['images'] if not img['alt']])
    pdf.multi_cell(0, 8, f"The Smart-Spider Vision system analyzed {len(data['images'])} visual assets. We detected {missing_alt} images missing 'alt-text' tags, which impacts accessibility and SEO rankings.")
    
    pdf.ln(5)
    
    # 5. Strategic AI Action Plan
    if action_plan:
        pdf.add_page() # Put this on a fresh new page
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "AI Strategic Action Plan", 0, 1)
        pdf.ln(5)
        
        pdf.set_font("Arial", "", 10)
        # Clean the text so FPDF doesn't crash on emojis or weird characters
        clean_plan = action_plan.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 8, clean_plan)
        pdf.ln(10)

    pdf.set_text_color(100)
    pdf.cell(0, 10, "*** End of Official Audit Report ***", 0, 1, 'C')

    return pdf.output(dest='S').encode('latin-1')